name: Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Create Firebase credentials file
        run: echo '${{ secrets.FIREBASE_CREDENTIALS }}' > firebase-credentials.json
      - name: Build with Maven
        run: mvn clean install
      - name: Run tests
        run: mvn test
